version: '3'

volumes:
  hermod-api_db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - hermod-api_db:/var/lib/mysql
  # ports:
    # - 3306:3306

  redis:
    image: redis
    restart: always
  # ports:
    # - 6379:6379

  webserver:
    build: ./
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 9090:9090
    # for debug purpose
    #    cap_add:
    #      - SYS_PTRACE

  worker:
    build: ./
    command: rq worker --url=redis://redis:6379
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
