version: '3'

volumes:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/mysql
  # ports:
    # - 3306:3306

  redis:
    image: redis
    restart: always

  worker:
    image: 127.0.0.1:5000/hermod-api
    build: .
    command: rq worker --url=redis://redis:6379
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    deploy:
      replicas: 1

  web:
    image: 127.0.0.1:5000/hermod-api
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - worker
    env_file:
      - .env
  # environment:
    # FLASK_ENV: development
    ports:
      - 9090:9090
  # cap_add:
    # - SYS_PTRACE
  # deploy:
    # replicas: 1
