version: '3'
services:
  hermod-api:
    build: .
    container_name: hermod-api
    ports:
      - 5000:5000
    volumes:
      - /data/hermod-api/config.ini:/usr/src/app/api/config.ini
      - /data/hermod-api/ovh.conf:/usr/src/app/api/ovh.conf
      - /data/hermod-api/data.db:/usr/src/app/api/data.db
    restart: unless-stopped
